### ISSUE TITLE
https://github.com/adafruit/Adafruit-Motor-HAT-Python-Library DEPRECATED

### ISSUE THREAD

**Issue by questrov** [Veilkrand/simplePiRover#1]
https://github.com/adafruit/Adafruit-Motor-HAT-Python-Library DEPRECATED see link to https://github.com/adafruit/Adafruit_CircuitPython_MotorKit 

Guess the code needs updated for the new Adafruit library, way over my head...

**Comment by Veilkrand** [comment]
Thanks for letting me know. There's no plan to update to the new package. However new Rover project will be available soon with new functionality

**Comment by Veilkrand** [comment]
Current master have been migrated to adafruit motorkit library
